### ISSUE TITLE
Clean up World

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#108]
The `World` contains a few things not needed:
* `Batch`s; they belong in the `RenderSystem`, not the `World`. 
* List of `Entity`s - they are already referenced in the `System`s, so why do we need it?

Inside `world.new()`:
* Initialization/adding of the `CameraSystem`. 
* Setting default `WorldBounds`. 

Side note:
* Where do we want to keep `WorldBounds`?

(I'm trying to keep the ECS as clean as possible; some cleaning up). 

@paked ?

**Comment by EtienneBruines** [comment]
I am going to take this one step further. 

Let's say we have three packages:
* `engi/ecs` - with things like `World`, `System`, `Entity` and `Component`, their definitions, and how they work. 
* `engi/systems` - with things like `RenderSystem`, `ComponentSystem`, etc.
* `engi` - which has the `run` functions, the main loop which calls `World.Update()`, and uses the two packages mentioned above. 

This would ensure the ecs-logic to be decoupled from the rest. Thoughts?

**Comment by matiwinnetou** [comment]
1. For me most natural is to have list of entities in the world. Also when we want to introduce scenes then it is most natural world holds reference to the entities.

**Comment by EtienneBruines** [comment]
1. Another use-case might be to change the way the `PauseSystem` works. It could be used to remove `Entity`s that are paused, from those `System`s. Then we would need the list in `World` to unpause (add them to the `System`s again).

**Comment by paked** [comment]
@EtienneBruines I don't really see a use-case for splitting up the package. We're not having of those sorts of issues yet.

**Comment by EtienneBruines** [comment]
@paked You could use ECS for anything you want, not just `engi`. It wouldn't crash when you tried to use it w/o engi / glfw.

**Comment by paked** [comment]
@EtienneBruines Hmmm. Ok, *that* is valid.

**Comment by paked** [comment]
I've merged in this PR. LMK if it is not finished.
