### ISSUE TITLE
Project's Todo List / Chat

### ISSUE THREAD

**Issue by pedronasser** [paked/engi#11]
I'm currently working on a game prototype using this engine, but there's a lot of things missing on it for now. So I'm currently committing only to my fork of this project.

Can we have a Trello's to-do list or at least any chat to sync this project's information?
Are you on Gopher's Slack? or IRC?

**Comment by paked** [comment]
I do have an invite to gophers slack, which I haven't claimed yet... I will join up and see if we can get an `engi` chat going.

**Comment by paked** [comment]
And on the topic of a to do list, historically we have just used the issues section. However, I think moving to trello would be a good idea.

**Comment by paked** [comment]
OK We are now `#engi` on http://gophers.slack.com

**Comment by JonnieCache** [comment]
What's wrong with IRC? I want to talk about this project but I don't want to sign up another account for something that has been free my entire life.

**Comment by paked** [comment]
Yeah @JonnieCache, If you want to chat with me personally though... I am `hcwool` on freenode, :+1::.

**Comment by JonnieCache** [comment]
nice one, see you on freenode at some point :wave:

**Comment by paked** [comment]
Closing because this seems to have been resolved.
