### ISSUE TITLE
Fix Pong Example

### ISSUE THREAD

**Issue by paked** [paked/engi#112]
When I run the Pong example on my OSX 10 El Capitan (Haven't tested other platforms) machine, it looks like the following image.

This probably has to do with the recent refractoring.

![screenshot 2015-11-30 06 12 44](https://cloud.githubusercontent.com/assets/8407370/11459372/660e3982-9729-11e5-9584-a698f10b5a80.png)

**Comment by EtienneBruines** [comment]
This has to do with the default values of the `CameraSystem`. I believe this will be fixed in the "Added Scenes"-patch, which should be available soon.

**Comment by EtienneBruines** [comment]
Same cause as #111.
