### ISSUE TITLE
Systems without Entities

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#119]
Maybe it doesn't completely capture the ECS paradigm, but it has happened to me more than once. 

Whenever the `System` has to do something with time (spawn creep after 5 seconds), or something with keys (show menu on ESC), I have to add a dummy `Entity` for this. If it doesn't have any `Entity`s, it's never called.

Would it be OK to call `Pre()` and `Post()` regardless of the amount of `Entity`s? @paked

**Comment by paked** [comment]
I had a discussion with a guy on the Gopher Slack about a similar issue.
Perhaps we should look at rewriting the way updates are handled. I propose
we let the author of the system do their own looping over each Entity, by
removing `Pre`/`Post` and having a single `Update(dt float32)` function
which is called once per frame, no matter what.

**Comment by EtienneBruines** [comment]
I had the same discussion, with (I guess) the same person ;-). 

I agree with its usefulness; I would however also like to have a way to not-worry about it. 

We could have this:

```go
type Systemer interface {
    Update(float32)
}

type System struct {
    // the way System is now
}

func (s *System) Update(dt float32) {
    // loop over entities, the way `World` does currently
}
```

And everywhere we now say `AddSystem`, use that interface instead of that struct. 

Thoughts @paked?
