### ISSUE TITLE
Windows as target platform

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#121]
As games who want to be released through [Steam Greenlight](https://steamcommunity.com/greenlight/faq/), Windows support is kinda a must. 

However, `engi` currently doesn't build with `GOOS=windows`.

**Comment by paked** [comment]
Do you happen to have a stacktrace/error?

**Comment by EtienneBruines** [comment]
Build errors:
```
../../../webgl/webgl_gl2.go:15:2: no buildable Go source files in /home/etiennebruines/workspaces/go/src/github.com/go-gl/gl/v2.1/gl
../../engi_glfw.go:20:2: no buildable Go source files in /home/etiennebruines/workspaces/go/src/github.com/go-gl/glfw/v3.1/glfw
../../audio.go:7:2: no buildable Go source files in /home/etiennebruines/workspaces/go/src/golang.org/x/mobile/exp/audio/al
```

**Comment by EtienneBruines** [comment]
When manually enabling `CGO_ENABLED=1`, the first two disappear; the last one stands.

**Comment by EtienneBruines** [comment]
Natively compiling on Windows leads to errors such as:
```
# golang.org/x/mobile/exp/audio/al
could not determine kind of name for C.AL_TRUE
could not determine kind of name for C.ALenum
could not determine kind of name for C.ALfloat
could not determine kind of name for C.ALint
...
```

**Comment by rof20004** [comment]
This error was corrected?

`
# runtime/cgo
gcc: error: unrecognized command line option ‘-mthreads’
`

**Comment by matiux** [comment]
I have the same issue
