### ISSUE TITLE
Cleanup after we're done

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#130]
Do we need actual cleanup? Or is this done when closing the program? (note that I am talking about stuff that's stored on the GPU RAM)

======

Examples of cleanup we might want:
* [ ] `Gl.DeleteProgram(program)`
    * This implicitly calls `Gl.DetachShader(shader)` and `Gl.DeleteShader(shader)`

**Comment by paked** [comment]
This is something which is done in most glfw programs. It would make sense that we have to do this – I doubt CGO does it for us!

**Comment by EtienneBruines** [comment]
Olivier Gagnon has confirmed that the GPU clears all GPU-RAM on termination. So we shouldn't need to worry about this.
