### ISSUE TITLE
What needs to happen in order to achieve support for Go 1.6?

### ISSUE THREAD

**Issue by paked** [paked/engi#149]
*note: currently don't have access to a computer which I can develop on, so I 0 idea if `engi` works or not already*

I've received paked/webgl#3 which should fix any go-gl issues. Does everything else work out of the box? I am specifically worried about our sound libraries.

cc: @faide @EtienneBruines

**Comment by EtienneBruines** [comment]
Everything works as it should, with the fix from https://github.com/paked/webgl/pull/3, audio as well.
