### ISSUE TITLE
API Elegance and usability

### ISSUE THREAD

**Issue by otraore** [paked/engi#164]
I'm requesting we use this issue to discuss API changes and suggestions. To start it off I'm recommended we change the 

```go
engi.Open(..., ...)
``` 
to
```go
engi.Run(..., ...)
``` 
I feel as if this is more clear and makes more sense.

**Comment by EtienneBruines** [comment]
As @paked and I have given this a thumbs up, this looks like something we can do.

**Comment by paked** [comment]
I'm thinking for further changes we should open new issues, instead of keeping it under one roof. Is this ok @otraore?

**Comment by otraore** [comment]
Yes no problem @paked, Originally planned to use this to discuss changes but that shouldn't be a problem once we have gitter set up.
