### ISSUE TITLE
Sprites

### ISSUE THREAD

**Issue by matiwinnetou** [paked/engi#18]
Does this game engine support sprite maps?

I would like to write a Galaxian game to learn this game engine and I found the following one big PNG file for a game:

http://www.spriters-resource.com/nes/galaxian/sheet/14344/

**Comment by paked** [comment]
Yes we do! Unfortunately, there isn't very much documentation... The component/system are in this file: https://github.com/paked/engi/blob/master/animation.go

If you need any help give me a shout!

**Comment by matiwinnetou** [comment]
:+1: 

BTW: it would be nicer if we had a Gitter channel, I am already signed by default to my work slack channel and Gitter is perfect for these things.

I already could comment on some things I encountered while browsing through the code.

**Comment by matiwinnetou** [comment]
I am trying the most simple sprite to work, I realized that *Region is renderable but Sprite is not really. Well there is a render method implemented but only a method that takes a *Batch. If I pass this to 
engi.NewRenderComponent(

it doesn't work because sprite cannot be rendered...

I modified tilemap example to play with latest API:

```package main

import (
	"fmt"
	"github.com/paked/engi"
	"log"
)

var World *GameWorld

type GameWorld struct {
	engi.World
}

func (game *GameWorld) Preload() {
	engi.Files.Add("data/Hero.png")

	log.Println("Preloaded")
}

func (game *GameWorld) Setup() {
	engi.SetBg(0x2d3739)

	game.AddSystem(&engi.RenderSystem{})

	sprites := engi.NewSpritesheet("Hero.png", 15, 15)
	cell := sprites.Cell(1)
	println(fmt.Sprintf("%f", sprites.Height()))
	println(fmt.Sprintf("%f", sprites.Width()))

	gameMap := engi.NewEntity([]string{"RenderSystem"})

	mapRender := engi.NewRenderComponent(cell, engi.Point{1, 1}, "map")
	mapSpace := engi.SpaceComponent{engi.Point{100, 100}, 0, 0}
	gameMap.AddComponent(&mapRender)
	gameMap.AddComponent(&mapSpace)

	game.AddEntity(gameMap)
}

func main() {
	World = &GameWorld{}
	engi.Open("Hello", 1024, 640, false, World)
}
```

so far no luck to be able to use one tile from the tilemap

**Comment by matiwinnetou** [comment]
there is this method:
```
func NewSprite(region *Region, x, y float32) *Sprite {
	return &Sprite{
		Position: &Point{x, y},
		Scale:    &Point{1, 1},
		Anchor:   &Point{0, 0},
		Rotation: 0,
		Color:    0xffffff,
		Alpha:    1,
		Region:   region,
	}
}

func (s *Sprite) Render(batch *Batch) {
	batch.Draw(s.Region, s.Position.X, s.Position.Y, s.Anchor.X, s.Anchor.Y, s.Scale.X, s.Scale.Y, s.Rotation, s.Color, s.Alpha)
}
```

but I cannot render a sprite...

**Comment by EtienneBruines** [comment]
Can you push the code to (a branch of) your fork? Then I could take a look? (easier when we're using the same code).
