### ISSUE TITLE
Remove Legacy Code

### ISSUE THREAD

**Issue by paked** [paked/engi#21]
Throughout the codebase there are various pieces of legacy code. These need to be removed.

* `Sprite`
* `Drawable` (or `Renderable`)

**Comment by EtienneBruines** [comment]
Can I ask what's wrong with `Drawable`, and how it should look instead?

**Comment by paked** [comment]
@EtienneBruines It fulfils the same purpose as `Renderable`, although... Perhaps we should use it... Renderable is quite ugly and relies on moving state.

**Comment by EtienneBruines** [comment]
@paked Using either one of those would indeed be better; as they both sound like they're doing the same.

**Comment by paked** [comment]
@EtienneBruines I personally think `Drawable` is the better design (not sure why I wrote it down then...)

cc: @matiwinnetou

**Comment by matiwinnetou** [comment]
very useful info, thx. Helps me to learn the current status of the project.

**Comment by paked** [comment]
@matiwinnetou Do you have any opinions on `Drawable` vs `Renderable`?

**Comment by matiwinnetou** [comment]
@paked At the moment sadly no, as I understand still too little the difference. In general, however, from my experience I can say that one should avoid state like fire. It is not always possible though or complicates code a lot. You mentioned that Drawable has no state where as Renderable assumes state.

In our ECS app, which believe or not is actually web application. (We created own ecs-web framework in Java 8 we have even various Worlds, like ImmutableWorld, RequestWorld (mutable world), to make this separation clear. In our design worlds form a chain, where a world can have a parent attached.

**Comment by paked** [comment]
@EtienneBruines What about you? (`Drawable` vs `Renderable` )

**Comment by EtienneBruines** [comment]
I do think the `Drawable` is much clearer. Since there'll be a `Shader` for each `PriorityLevel` (which people can add themselves), all we need from whatever we want to draw, is the `Texture`, and size/location. 

I have no idea what the `View() (float32, float32, float32, float32)` function is supposed to do though.
