### ISSUE TITLE
Use different Shader for HUD

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#22]
`HUDGround` is defined in `system.go`, to indicate some kind of HUD. This is good. 

This is given a `PriorityLevel`, to indicate it must be drawn on top. (i.e. `Background` is all at the bottom). 

However, the HUD is no affected by the camera (shouldn't move / change size). Since the camera behavior is defined in the Shader (`assets.go`, lines 248 and up), we should use other definitions for the HUD. 

Related is also `batch.go`, line 44.

**Comment by paked** [comment]
*assigns @EtienneBruines*

**Comment by EtienneBruines** [comment]
In order to create the hud demo at https://github.com/EtienneBruines/engi/tree/hud, I had to make `Batch` and the shaders, public. 

The question is: is this OK? 

At some point, the user will have to tell `engi`: this `PriorityLevel` is affected by the `Camera`, or isn't (`HUD`). The demo does that by creating a `Batch`, and adding it. But perhaps there's another (better) solution?
