### ISSUE TITLE
Give Camera Safe Defaults

### ISSUE THREAD

**Issue by paked** [paked/engi#26]
I believe this should be no zoom.

**Comment by paked** [comment]
cc: @EtienneBruines

**Comment by EtienneBruines** [comment]
Camera has default zoom value of `1.00`, this is usually equal to "no zoom". 

However, `(0, 0)` is at the center of the screen. Perhaps I can try and move this a bit such that it becomes upper-left-corner?

**Comment by paked** [comment]
Sure.
