### ISSUE TITLE
Consistency between Type and Name

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#32]
Some interfaces require implementation of the `Name() string` function, while others require the `Type() string` function. 

Both are implemented in exactly the same way (which could also be done by `reflect`, but that's another story). We should create some consistency and use either one of those. 

Thoughts on which one?

**Comment by paked** [comment]
@EtienneBruines I vote `Type()`

**Comment by EtienneBruines** [comment]
Shall I make a PR for this?

**Comment by paked** [comment]
SGTM!
