### ISSUE TITLE
Cleanup: engi has both responder and Wo - global

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#35]
In `engi.go`, two variables are globally defined:

```go
var (
	responder   Responder
	Wo          Responder
)
```
They have exactly the same value, and are used for exactly the same. Which one are we keeping? 

Side-node, if it's a `Responder` (and not a `World`), should we even call it `Wo`? It took me a while before I noticed why `Wo` didn't have the functions / variables available that `World` has.

**Comment by EtienneBruines** [comment]
And I wonder if we should keep the distinction between `Responder` and `World`? It looks nice, but is there any implementation of `Responder` that isn't `World`, that would make sense?

**Comment by paked** [comment]
I originally made `World` different to `Responder` because it would make it easier to implement... I see now that is isn't an optimal solution. I'd suggest removing Responder altogether.

**Comment by EtienneBruines** [comment]
It may be optimal, just didn't see the point in it ;-).

Shall I make a PR for that as well?

**Comment by EtienneBruines** [comment]
Found out, `Responder` did serve a useful purpose. 

One could easily create his own (`Game`), and then pass that along.

**Comment by paked** [comment]
@EtienneBruines Yes. Are we anticipating people will want to make their own Game's though?

**Comment by EtienneBruines** [comment]
We at least want them to pass a `Setup()` function, and perhaps a `Close()` / `Cleanup()` function?

**Comment by paked** [comment]
@EtienneBruines I believe it is more idiomatic to use the second option. Unless we were to go full events (ie. `Worlds.HandleFunc(e engi.SetupEvent, f func(c engi.Contenxter))`), which I do not think is the direction we should be heading in

**Comment by EtienneBruines** [comment]
So, to be sure, we'd want something like:

```go
type Game interface {
    Setup(*engi.World)
}
```

to which we could possibly add stuff if we'd want to.

**Comment by paked** [comment]
Ok. Do we know if this would kill the existing implementation of Responder?

**Comment by EtienneBruines** [comment]
Yes and no. 

Those things that are happening in `Preload()`, will now have to happen in `Setup()` - which is OK, since they basically were meant for the same thing.

**Comment by paked** [comment]
@EtienneBruines I'd like to see an implementation of this. It seems like it could be worth doing.

**Comment by matiwinnetou** [comment]
@paked: it is a voluntary work, it would be unfair to require this from Etienne :)

**Comment by EtienneBruines** [comment]
Still, doesn't sound like a lot of work ;-). 

I won't be able to do this in a separate PR; but I can manage to do this in the major changes I've done to `AudioSystem` and `CameraSystem`?

(Then again, if anyone else would like to do it instead; I don't want to take away potential nice tasks)

**Comment by EtienneBruines** [comment]
@paked @matiwinnetou The idea / implementation is fairly simple, I now have this:

```go
type CustomGame interface {
    // Preload is the place where you define assets/files you might need, before they will be loaded
    Preload()
    // Setup is where you define your Entities, Components and Systems. 
    Setup(*World)
}
```

The tricky part is this. For keys that are pressed, one just had to check whether their `State` was `.Down()` or not. However, in the current (read: old) implementation, the `Scroll` was handled by a `Scroll` method on the interface. 

Now I'm wondering, what the best way is to handle the Scroll events. Perhaps allow for the same construction as with the keys (check if their `State` is `Scrolled Up` or something), and on top of that, implement some kind of `MouseMessage`, to which their Systems can listen for events?

**Comment by matiwinnetou** [comment]
@paked @EtienneBruines For me there are some generic things I would like to discuss with design of world. In our implementation, we allow people to loop through all entities in the world and do something for certain components in those entities. Here I can see this is missing, update function takes entity and delta time. It doesn't seem like I have access to other entities.

**Comment by paked** [comment]
@matiwinnetou @EtienneBruines Sorry if I came off forceful with that comment. I only meant that it would be an interesting avenue to explore.

**Comment by paked** [comment]
@matiwinnetou Doesn't messaging a system that contains those entities solve that problem?

**Comment by paked** [comment]
I'd rather stick without handlers for the input interfacing

**Comment by EtienneBruines** [comment]
And by handlers you mean `Callback` handlers, or a function people need to implement as part of an `interface`?

Or would you rather have them check the state of the last input in a way that the `Keys` are done currently?

**Comment by paked** [comment]
I'd rather keep it analogous to the rest of the input methods

**Comment by EtienneBruines** [comment]
Currently, that means checking their state on an `Update` function, without special handlers.
