### ISSUE TITLE
DoesExist and Hide 

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#64]
This issue is two-fold:

* [ ] Remove the `DoesExist` function from the `Entitiy`s;
* [ ] Add a `Hidden` `PriorityLevel` to `system.go`, with a negative value (lower than `Background`); this will allow objects to not be rendered by `RenderSystem`. This can be set by the user in the `RenderComponent` the user adds.

It's open for anyone who wants to do this.

**Comment by matiwinnetou** [comment]
Done, pull req open.

**Comment by EtienneBruines** [comment]
resolved as of #69 .
