### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#67]
Some things in `engi` don't have idiomatic names.

Examples are:
* `engi.GetComponent` -> `engi.Component`
* `engi.Keys.KEY_SPACE` -> `engi.Keys.SPACE`

Also: we might want to think about removing `engi.Keys.SPACE` (and such) all-together? Since we have `engi.Keys.Get(engi.Space)` - which works for every key, and not just a few of them?

**Comment by paked** [comment]
Remove the redundancy!

**Comment by matiwinnetou** [comment]
https://github.com/paked/engi/pull/84

**Comment by matiwinnetou** [comment]
My pull request doesn't fix the issue of engi.GetComponent vs Component but I think it is better to do this in steps.

**Comment by matiwinnetou** [comment]
done

**Comment by paked** [comment]
:+1:
