### ISSUE TITLE
Changing PriorityLevel

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#72]
Right now, when changing the `Priority` in a `RenderComponent`, it doesn't get rendered correctly. 

The current workaround is to add the `Entity` to the world again, to ensure the `RenderSystem` categorizes things correctly. 

Note that this is because of the `rendersystem.changed` variable, which makes sure the per-`PriorityLevel` list doesn't have to get rebuild on each frame.

**Comment by EtienneBruines** [comment]
Wow, this surely looks like a bug in Github. 

A fork has a patch, and the original issue get closed :astonished:

**Comment by paked** [comment]
weird.

**Comment by EtienneBruines** [comment]
This kinda is fixed (so no need to fix it), but still awaiting a PR from @matiwinnetou. No hurries.

**Comment by paked** [comment]
:+1:

**Comment by EtienneBruines** [comment]
Fixed as of #69.

**Comment by mewmew** [comment]
> Wow, this surely looks like a bug in Github.
> 
> A fork has a patch, and the original issue get closed :astonished:

Did you report this issue to GitHub?

**Comment by EtienneBruines** [comment]
@mewmew It was non-repeatable, so no.

**Comment by mewmew** [comment]
> @mewmew It was non-reproducable, so no.

I see, still interesting bug.
