### ISSUE TITLE
Automatically add Systems

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#74]
In the `README.md` file, it reads:
* Automatically detect which systems should be added to based off component depends on

It's a nice idea, and I would like to use this issue to talk about it - possibly 'accepting' or 'rejecting' it as an idea. 

-----
### Pros
* Easier to for the user, no need to manually add those Systems.

### Cons
* We possibly don't know the `System` - if it's `RenderSystem`, we know it. But if it's some kind of `MyCustomSystem`, then we wouldn't be able to add it;
* It's slower, if we have to check "did we add `System` this already?" whenever an `Entity` is added.

**Comment by matiwinnetou** [comment]
I would say this is ready advanced function if ever to do. Our ECS doesn't even come close to this.

There is also element of magic with this so I would be really skeptical and overall I would be careful with this feature.

**Comment by paked** [comment]
I *really* would like this. I think it removes so much user error.

**Comment by EtienneBruines** [comment]
@paked do we want this for all (possibly user-defined) `System`s, or just for the ones `engi` has? (i.e. `RenderSystem`, `AudioSstem`, ...)

**Comment by EtienneBruines** [comment]
Now that we have scenes, I think we could define some kind of `AddDefaultSystem`?

Usage:

```go
engi.AddDefaultSystem(&engi.RenderSystem{})
```

And for each `Scene` that gets created, that same `engi.RenderSystem` could get reinitialized, without having to specify "I want a `RenderSystem`", for every `Scene`. 

### Downside
i.e. the `RenderSystem` is kinda state-dependent: it needs a list of `Entity`s to work with, and that changes from `Scene` to `Scene`. So maybe we need to work with some kind of initializer, of type `func() Systemer` or something.

**Comment by paked** [comment]
@EtienneBruines I don't think this is worth it. We are leaving ourselves open to a *lot* of confusion IMO.

**Comment by paked** [comment]
This should be closed unless you have another idea.
