### ISSUE TITLE
Scenes in ECS

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#77]
With the term `Scene`, I mean something that fills the screen. Such as "level 1 in pacman", or "main menu", or "settings", or "high scores". 

How should one handle this / switch between them, in ECS / engi? 

My original thought was to add / remove `System`s on-the-fly, indicating which would be active and which would not. I am not sure if this is the best/correct way to go, or if there's another (more idiomatic) approach?

**Comment by paked** [comment]
I think that instead of doing this with Systems, we should allow switching between `World`s or `CustomGame`s.

**Comment by matiwinnetou** [comment]
:+1: @paked
