### ISSUE TITLE
Ideally each ECS system and component should be in own go file

### ISSUE THREAD

**Issue by matiwinnetou** [paked/engi#79]
Imagine we had `render.go` where `RenderSystem` and `RenderComponent` would go, etc

Now it is a bit tricky to navigate around the code, this would make it much easier. Gray areas we could still discuss.

**Comment by EtienneBruines** [comment]
Same goes for `CollisionSystem` and `CollisionComponent`.

**Comment by matiwinnetou** [comment]
Same may go for a few things. It was just an example.

**Comment by EtienneBruines** [comment]
Let's create a list? (preferably in the first post in this issue)

**Comment by matiwinnetou** [comment]
I started doing this to prototype this. It bothers me personally this situation at the moment.

**Comment by matiwinnetou** [comment]
https://github.com/paked/engi/pull/81

**Comment by matiwinnetou** [comment]
Done
