### ISSUE TITLE
code.google.com shutting down

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#8]
```
warning: code.google.com is shutting down; import path code.google.com/p/freetype-go/freetype will stop working
warning: code.google.com is shutting down; import path code.google.com/p/freetype-go/freetype/raster will stop working
warning: code.google.com is shutting down; import path code.google.com/p/freetype-go/freetype/truetype will stop working
```

These are referenced at `font.go`, and should be replaced with the new import path (`github.com/golang/freetype`).

**Comment by paked** [comment]
So, I tried making the changes and rewrites using these libraries (https://github.com/golang/freetype, https://github.com/fnkr/golang-freetype).

**Comment by EtienneBruines** [comment]
Guess you haven't pushed it to the repository yet. Since code.google.com is now officially not working any more, perhaps you should. 

I could create a PR if you want, but you can also just edit `font.go` to use `github.com/golang/freetype`.
