### ISSUE TITLE
FPS Limit

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#9]
When using the example given at the README, I'm getting a FPS of about 30-40k. 

It would be nice if we could limit this, since this wastes quite some CPU resources. The programmer could pass/set options somewhere, to set the limit to 30/60/90/120/unlimited whenever he wants. Preferably at runtime (because it'll reside in the game Settings). 

Looking at the code [here](https://github.com/paked/engi/blob/master/engi_glfw.go#L125-L132), it's obvious why the FPS is getting this high. 

What about something like this?

```go

	Wo.New()
	ticker := time.NewTicker(time.Duration(int(time.Second) / fpsLimit))

Outer:
	for {
		select {
		case <-ticker.C:
			responder.Update(Time.Delta())
			window.SwapBuffers()
			glfw.PollEvents()
			keysUpdate()
			Time.Tick()
			if window.ShouldClose() {
			    break Outer
			}
		}
	}
    ticker.Stop()
```

Not sure what the best practice would be if someone were to change the fpsLimit - we'd have to re-create the ticker.

**Comment by paked** [comment]
Well looking at the exposed functions, we would have to recreate it. I personally am happy with this solution, it's not like people would recreate the ticker every frame.

**Comment by EtienneBruines** [comment]
Would you prefer this to be handled as a static function, such as the `SetBackground` function? i.e. 
```go
func SetFPSLimit (fps int) {
    ....
}
```

Or tied to any running instance of some sort?

**Comment by paked** [comment]
Static seems to be the only possible way to do it right now, without a massive restructure. :)

**Comment by pedronasser** [comment]
LGTM
