### ISSUE TITLE
System New does not have access to system.World

### ISSUE THREAD

**Issue by EtienneBruines** [paked/engi#93]
The `system.World` variable is being set after the `system.New()` function is being called. 

As such, one does not have access to the `World` from the `system.New()` function (null-reference). This should be fixed by simply switching two lines: first calling `SetWorld`, then calling `New()`.

**Comment by EtienneBruines** [comment]
Apparently, this was not as easy as I thought:

* `system.world` (the variable), gets reset on `system = NewSystem()`, which is being called in most `New()` functions;
* `system` is initialized in the `New()` function, so there's no `system` of which we can set the `world` variable. 

Thoughts @paked?

**Comment by paked** [comment]
@EtienneBruines Your proposed solution sounds good to me. I feel it works much better with ECS.
